//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBRouting.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBRouteEntities : DbContext
    {
        public DBRouteEntities()
            : base("name=DBRouteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<RouteTable> RouteTables { get; set; }
        public virtual DbSet<Master_Roles> Master_Roles { get; set; }
        public virtual DbSet<Roles_Controller> Roles_Controller { get; set; }
        public virtual DbSet<User_Roles> User_Roles { get; set; }

        public System.Data.Entity.DbSet<DBRouting.Models.UserRole> UserRoles { get; set; }
    }
}
